storage:
  host: "postgres"
  port: 5432
  database: "orders-db"
  user: "postgres"
  password: "postgres"
  migrations: true
  ssl_mode: "disable"

server:
  address: "0.0.0.0"
  port: "8080"
  timeout: "30s"
  idle_timeout: "120s"

message_broker:
  address: "kafka:9093"
  orders_topic: "orders"
  saver_group: "saver-group"
  broadcaster_group: "broadcaster-group"
  create_topic: true
  session_timeout: "30s"
  max_poll_interval: "5m"

logging:
  level: "info"
  format: "json"

cache:
  ttl: "15m"
  cleanup_interval: "1h"