version: "2"
sql:
  - engine: "postgresql"
    queries: "./queries/"
    schema: "./../../migrations/"
    gen:
      go:
        out: "./gen/"
        package: "gen"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_exact_table_names: false